// AUTO-GENERATED by scripts/generate-jobs-index.mjs
// Total jobs: 500

export const JOB_INDEX = [
  {
    "title": "Administrative Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Customer Service Representative",
    "template": "customer_support"
  },
  {
    "title": "Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Software Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Systems Administrator",
    "template": "it_ops"
  },
  {
    "title": "Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Registered Nurse",
    "template": "healthcare_clinical"
  },
  {
    "title": "Teacher",
    "template": "education"
  },
  {
    "title": "Graphic Designer",
    "template": "creative_media"
  },
  {
    "title": "Electrician",
    "template": "skilled_trades"
  },
  {
    "title": "Truck Driver",
    "template": "logistics_transport"
  },
  {
    "title": "Executive Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Customer Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Inside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Frontend Developer",
    "template": "software_engineering"
  },
  {
    "title": "Network Administrator",
    "template": "it_ops"
  },
  {
    "title": "Staff Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Licensed Practical Nurse",
    "template": "healthcare_clinical"
  },
  {
    "title": "Elementary School Teacher",
    "template": "education"
  },
  {
    "title": "UI Designer",
    "template": "creative_media"
  },
  {
    "title": "Plumber",
    "template": "skilled_trades"
  },
  {
    "title": "Delivery Driver",
    "template": "logistics_transport"
  },
  {
    "title": "Receptionist",
    "template": "clerical_admin"
  },
  {
    "title": "Client Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Outside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Backend Developer",
    "template": "software_engineering"
  },
  {
    "title": "IT Support Specialist",
    "template": "it_ops"
  },
  {
    "title": "Senior Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Nurse Practitioner",
    "template": "healthcare_clinical"
  },
  {
    "title": "Middle School Teacher",
    "template": "education"
  },
  {
    "title": "UX Designer",
    "template": "creative_media"
  },
  {
    "title": "HVAC Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Courier",
    "template": "logistics_transport"
  },
  {
    "title": "Office Manager",
    "template": "clerical_admin"
  },
  {
    "title": "Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Account Executive",
    "template": "sales_marketing"
  },
  {
    "title": "Full Stack Developer",
    "template": "software_engineering"
  },
  {
    "title": "IT Technician",
    "template": "it_ops"
  },
  {
    "title": "Bookkeeper",
    "template": "finance_accounting"
  },
  {
    "title": "Physician Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "High School Teacher",
    "template": "education"
  },
  {
    "title": "Product Designer",
    "template": "creative_media"
  },
  {
    "title": "Welder",
    "template": "skilled_trades"
  },
  {
    "title": "Dispatcher",
    "template": "logistics_transport"
  },
  {
    "title": "Office Administrator",
    "template": "clerical_admin"
  },
  {
    "title": "Technical Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Account Manager",
    "template": "sales_marketing"
  },
  {
    "title": "Mobile Developer",
    "template": "software_engineering"
  },
  {
    "title": "IT Analyst",
    "template": "it_ops"
  },
  {
    "title": "Accounting Specialist",
    "template": "finance_accounting"
  },
  {
    "title": "Medical Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Special Education Teacher",
    "template": "education"
  },
  {
    "title": "Motion Designer",
    "template": "creative_media"
  },
  {
    "title": "Carpenter",
    "template": "skilled_trades"
  },
  {
    "title": "Logistics Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Operations Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Help Desk Representative",
    "template": "customer_support"
  },
  {
    "title": "Sales Development Representative",
    "template": "sales_marketing"
  },
  {
    "title": "iOS Developer",
    "template": "software_engineering"
  },
  {
    "title": "DevOps Engineer",
    "template": "it_ops"
  },
  {
    "title": "Accounts Payable Specialist",
    "template": "finance_accounting"
  },
  {
    "title": "Clinical Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Substitute Teacher",
    "template": "education"
  },
  {
    "title": "Video Editor",
    "template": "creative_media"
  },
  {
    "title": "Machinist",
    "template": "skilled_trades"
  },
  {
    "title": "Supply Chain Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Administrative Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Call Center Agent",
    "template": "customer_support"
  },
  {
    "title": "Business Development Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Android Developer",
    "template": "software_engineering"
  },
  {
    "title": "Site Reliability Engineer",
    "template": "it_ops"
  },
  {
    "title": "Accounts Receivable Specialist",
    "template": "finance_accounting"
  },
  {
    "title": "Physical Therapist",
    "template": "healthcare_clinical"
  },
  {
    "title": "College Professor",
    "template": "education"
  },
  {
    "title": "Content Creator",
    "template": "creative_media"
  },
  {
    "title": "Maintenance Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Warehouse Associate",
    "template": "logistics_transport"
  },
  {
    "title": "Program Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Customer Success Associate",
    "template": "customer_support"
  },
  {
    "title": "Marketing Specialist",
    "template": "sales_marketing"
  },
  {
    "title": "Web Developer",
    "template": "software_engineering"
  },
  {
    "title": "Cloud Engineer",
    "template": "it_ops"
  },
  {
    "title": "Payroll Specialist",
    "template": "finance_accounting"
  },
  {
    "title": "Occupational Therapist",
    "template": "healthcare_clinical"
  },
  {
    "title": "Adjunct Professor",
    "template": "education"
  },
  {
    "title": "Copywriter",
    "template": "creative_media"
  },
  {
    "title": "Industrial Maintenance Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Warehouse Supervisor",
    "template": "logistics_transport"
  },
  {
    "title": "Scheduling Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Customer Success Specialist",
    "template": "customer_support"
  },
  {
    "title": "Digital Marketing Specialist",
    "template": "sales_marketing"
  },
  {
    "title": "QA Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Infrastructure Engineer",
    "template": "it_ops"
  },
  {
    "title": "Financial Analyst",
    "template": "finance_accounting"
  },
  {
    "title": "Respiratory Therapist",
    "template": "healthcare_clinical"
  },
  {
    "title": "Teaching Assistant",
    "template": "education"
  },
  {
    "title": "Content Writer",
    "template": "creative_media"
  },
  {
    "title": "Field Service Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Forklift Operator",
    "template": "logistics_transport"
  },
  {
    "title": "Data Entry Clerk",
    "template": "clerical_admin"
  },
  {
    "title": "Customer Success Manager",
    "template": "customer_support"
  },
  {
    "title": "Marketing Coordinator",
    "template": "sales_marketing"
  },
  {
    "title": "Test Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Security Analyst",
    "template": "it_ops"
  },
  {
    "title": "Senior Financial Analyst",
    "template": "finance_accounting"
  },
  {
    "title": "Radiology Technologist",
    "template": "healthcare_clinical"
  },
  {
    "title": "Instructional Designer",
    "template": "education"
  },
  {
    "title": "Technical Writer",
    "template": "creative_media"
  },
  {
    "title": "Automotive Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Inventory Specialist",
    "template": "logistics_transport"
  },
  {
    "title": "Records Clerk",
    "template": "clerical_admin"
  },
  {
    "title": "Service Desk Analyst",
    "template": "customer_support"
  },
  {
    "title": "Marketing Manager",
    "template": "sales_marketing"
  },
  {
    "title": "Automation Engineer",
    "template": "software_engineering"
  },
  {
    "title": "SOC Analyst",
    "template": "it_ops"
  },
  {
    "title": "FP&A Analyst",
    "template": "finance_accounting"
  },
  {
    "title": "Ultrasound Technologist",
    "template": "healthcare_clinical"
  },
  {
    "title": "Academic Advisor",
    "template": "education"
  },
  {
    "title": "Social Media Producer",
    "template": "creative_media"
  },
  {
    "title": "Diesel Mechanic",
    "template": "skilled_trades"
  },
  {
    "title": "Shipping and Receiving Clerk",
    "template": "logistics_transport"
  },
  {
    "title": "Clerical Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Support Analyst",
    "template": "customer_support"
  },
  {
    "title": "Social Media Manager",
    "template": "sales_marketing"
  },
  {
    "title": "Data Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Incident Response Analyst",
    "template": "it_ops"
  },
  {
    "title": "Finance Manager",
    "template": "finance_accounting"
  },
  {
    "title": "Pharmacy Technician",
    "template": "healthcare_clinical"
  },
  {
    "title": "School Counselor",
    "template": "education"
  },
  {
    "title": "Creative Strategist",
    "template": "creative_media"
  },
  {
    "title": "CNC Operator",
    "template": "skilled_trades"
  },
  {
    "title": "Transportation Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Office Clerk",
    "template": "clerical_admin"
  },
  {
    "title": "IT Help Desk Technician",
    "template": "customer_support"
  },
  {
    "title": "SEO Specialist",
    "template": "sales_marketing"
  },
  {
    "title": "Platform Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Identity and Access Management Specialist",
    "template": "it_ops"
  },
  {
    "title": "Billing Specialist",
    "template": "finance_accounting"
  },
  {
    "title": "Clinical Laboratory Technician",
    "template": "healthcare_clinical"
  },
  {
    "title": "Curriculum Specialist",
    "template": "education"
  },
  {
    "title": "Art Director",
    "template": "creative_media"
  },
  {
    "title": "Tool and Die Maker",
    "template": "skilled_trades"
  },
  {
    "title": "Fleet Manager",
    "template": "logistics_transport"
  },
  {
    "title": "Document Control Specialist",
    "template": "clerical_admin"
  },
  {
    "title": "Product Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "PPC Specialist",
    "template": "sales_marketing"
  },
  {
    "title": "DevSecOps Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Network Engineer",
    "template": "it_ops"
  },
  {
    "title": "Revenue Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Paramedic",
    "template": "healthcare_clinical"
  },
  {
    "title": "Learning and Development Specialist",
    "template": "education"
  },
  {
    "title": "Brand Designer",
    "template": "creative_media"
  },
  {
    "title": "Millwright",
    "template": "skilled_trades"
  },
  {
    "title": "Route Planner",
    "template": "logistics_transport"
  },
  {
    "title": "Front Desk Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Client Services Representative",
    "template": "customer_support"
  },
  {
    "title": "Email Marketing Specialist",
    "template": "sales_marketing"
  },
  {
    "title": "Machine Learning Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Systems Engineer",
    "template": "it_ops"
  },
  {
    "title": "Cost Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "EMT",
    "template": "healthcare_clinical"
  },
  {
    "title": "Corporate Trainer",
    "template": "education"
  },
  {
    "title": "Photographer",
    "template": "creative_media"
  },
  {
    "title": "Instrumentation Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Operations Supervisor",
    "template": "logistics_transport"
  },
  {
    "title": "Personal Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Client Relations Specialist",
    "template": "customer_support"
  },
  {
    "title": "Content Marketing Specialist",
    "template": "sales_marketing"
  },
  {
    "title": "Game Developer",
    "template": "software_engineering"
  },
  {
    "title": "Database Administrator",
    "template": "it_ops"
  },
  {
    "title": "Tax Associate",
    "template": "finance_accounting"
  },
  {
    "title": "Dental Hygienist",
    "template": "healthcare_clinical"
  },
  {
    "title": "Senior Teacher",
    "template": "education"
  },
  {
    "title": "Videographer",
    "template": "creative_media"
  },
  {
    "title": "Boilermaker",
    "template": "skilled_trades"
  },
  {
    "title": "Distribution Associate",
    "template": "logistics_transport"
  },
  {
    "title": "Mailroom Clerk",
    "template": "clerical_admin"
  },
  {
    "title": "Customer Experience Specialist",
    "template": "customer_support"
  },
  {
    "title": "Content Marketing Manager",
    "template": "sales_marketing"
  },
  {
    "title": "Unity Developer",
    "template": "software_engineering"
  },
  {
    "title": "IT Operations Manager",
    "template": "it_ops"
  },
  {
    "title": "Tax Analyst",
    "template": "finance_accounting"
  },
  {
    "title": "Speech Language Pathologist",
    "template": "healthcare_clinical"
  },
  {
    "title": "Lead Teacher",
    "template": "education"
  },
  {
    "title": "Animator",
    "template": "creative_media"
  },
  {
    "title": "Painter",
    "template": "skilled_trades"
  },
  {
    "title": "Senior Truck Driver",
    "template": "logistics_transport"
  },
  {
    "title": "File Clerk",
    "template": "clerical_admin"
  },
  {
    "title": "Customer Care Specialist",
    "template": "customer_support"
  },
  {
    "title": "Brand Manager",
    "template": "sales_marketing"
  },
  {
    "title": "Unreal Engine Developer",
    "template": "software_engineering"
  },
  {
    "title": "Systems Operations Analyst",
    "template": "it_ops"
  },
  {
    "title": "Audit Associate",
    "template": "finance_accounting"
  },
  {
    "title": "Behavioral Health Technician",
    "template": "healthcare_clinical"
  },
  {
    "title": "Assistant Teacher",
    "template": "education"
  },
  {
    "title": "Sound Designer",
    "template": "creative_media"
  },
  {
    "title": "Roofer",
    "template": "skilled_trades"
  },
  {
    "title": "Lead Truck Driver",
    "template": "logistics_transport"
  },
  {
    "title": "Administrative Specialist",
    "template": "clerical_admin"
  },
  {
    "title": "Account Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Growth Marketer",
    "template": "sales_marketing"
  },
  {
    "title": "API Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Endpoint Administrator",
    "template": "it_ops"
  },
  {
    "title": "Internal Auditor",
    "template": "finance_accounting"
  },
  {
    "title": "Senior Registered Nurse",
    "template": "healthcare_clinical"
  },
  {
    "title": "Associate Teacher",
    "template": "education"
  },
  {
    "title": "Senior Graphic Designer",
    "template": "creative_media"
  },
  {
    "title": "Senior Electrician",
    "template": "skilled_trades"
  },
  {
    "title": "Assistant Truck Driver",
    "template": "logistics_transport"
  },
  {
    "title": "Project Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Senior Customer Service Representative",
    "template": "customer_support"
  },
  {
    "title": "Demand Generation Manager",
    "template": "sales_marketing"
  },
  {
    "title": "Integration Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Help Desk Technician",
    "template": "it_ops"
  },
  {
    "title": "Controller",
    "template": "finance_accounting"
  },
  {
    "title": "Lead Registered Nurse",
    "template": "healthcare_clinical"
  },
  {
    "title": "Director of Teacher",
    "template": "education"
  },
  {
    "title": "Lead Graphic Designer",
    "template": "creative_media"
  },
  {
    "title": "Lead Electrician",
    "template": "skilled_trades"
  },
  {
    "title": "Associate Truck Driver",
    "template": "logistics_transport"
  },
  {
    "title": "Business Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Lead Customer Service Representative",
    "template": "customer_support"
  },
  {
    "title": "Partnerships Manager",
    "template": "sales_marketing"
  },
  {
    "title": "Junior Software Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Senior Systems Administrator",
    "template": "it_ops"
  },
  {
    "title": "Treasury Analyst",
    "template": "finance_accounting"
  },
  {
    "title": "Charge Registered Nurse",
    "template": "healthcare_clinical"
  },
  {
    "title": "Senior Elementary School Teacher",
    "template": "education"
  },
  {
    "title": "Assistant Graphic Designer",
    "template": "creative_media"
  },
  {
    "title": "Apprentice Electrician",
    "template": "skilled_trades"
  },
  {
    "title": "Manager Truck Driver",
    "template": "logistics_transport"
  },
  {
    "title": "Facilities Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 1 Customer Service Representative",
    "template": "customer_support"
  },
  {
    "title": "Sales Operations Analyst",
    "template": "sales_marketing"
  },
  {
    "title": "Senior Software Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Lead Systems Administrator",
    "template": "it_ops"
  },
  {
    "title": "Budget Analyst",
    "template": "finance_accounting"
  },
  {
    "title": "Clinical Registered Nurse",
    "template": "healthcare_clinical"
  },
  {
    "title": "Lead Elementary School Teacher",
    "template": "education"
  },
  {
    "title": "Associate Graphic Designer",
    "template": "creative_media"
  },
  {
    "title": "Journeyman Electrician",
    "template": "skilled_trades"
  },
  {
    "title": "Senior Delivery Driver",
    "template": "logistics_transport"
  },
  {
    "title": "Executive Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 2 Customer Service Representative",
    "template": "customer_support"
  },
  {
    "title": "Revenue Operations Analyst",
    "template": "sales_marketing"
  },
  {
    "title": "Lead Software Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Junior Systems Administrator",
    "template": "it_ops"
  },
  {
    "title": "Lead Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Senior Licensed Practical Nurse",
    "template": "healthcare_clinical"
  },
  {
    "title": "Assistant Elementary School Teacher",
    "template": "education"
  },
  {
    "title": "Director of Graphic Designer",
    "template": "creative_media"
  },
  {
    "title": "Senior Plumber",
    "template": "skilled_trades"
  },
  {
    "title": "Lead Delivery Driver",
    "template": "logistics_transport"
  },
  {
    "title": "Senior Administrative Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 3 Customer Service Representative",
    "template": "customer_support"
  },
  {
    "title": "Senior Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Principal Software Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Manager Systems Administrator",
    "template": "it_ops"
  },
  {
    "title": "Associate Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Lead Licensed Practical Nurse",
    "template": "healthcare_clinical"
  },
  {
    "title": "Associate Elementary School Teacher",
    "template": "education"
  },
  {
    "title": "Senior UI Designer",
    "template": "creative_media"
  },
  {
    "title": "Lead Plumber",
    "template": "skilled_trades"
  },
  {
    "title": "Assistant Delivery Driver",
    "template": "logistics_transport"
  },
  {
    "title": "Lead Administrative Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Senior Customer Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Lead Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Staff Software Engineer",
    "template": "software_engineering"
  },
  {
    "title": "Director of Systems Administrator",
    "template": "it_ops"
  },
  {
    "title": "Manager Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Charge Licensed Practical Nurse",
    "template": "healthcare_clinical"
  },
  {
    "title": "Director of Elementary School Teacher",
    "template": "education"
  },
  {
    "title": "Lead UI Designer",
    "template": "creative_media"
  },
  {
    "title": "Apprentice Plumber",
    "template": "skilled_trades"
  },
  {
    "title": "Associate Delivery Driver",
    "template": "logistics_transport"
  },
  {
    "title": "Assistant Administrative Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Lead Customer Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Associate Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Junior Frontend Developer",
    "template": "software_engineering"
  },
  {
    "title": "Senior Network Administrator",
    "template": "it_ops"
  },
  {
    "title": "Director of Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Clinical Licensed Practical Nurse",
    "template": "healthcare_clinical"
  },
  {
    "title": "Senior Middle School Teacher",
    "template": "education"
  },
  {
    "title": "Assistant UI Designer",
    "template": "creative_media"
  },
  {
    "title": "Journeyman Plumber",
    "template": "skilled_trades"
  },
  {
    "title": "Manager Delivery Driver",
    "template": "logistics_transport"
  },
  {
    "title": "Associate Administrative Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 1 Customer Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Manager Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Senior Frontend Developer",
    "template": "software_engineering"
  },
  {
    "title": "Lead Network Administrator",
    "template": "it_ops"
  },
  {
    "title": "Senior Staff Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Senior Nurse Practitioner",
    "template": "healthcare_clinical"
  },
  {
    "title": "Lead Middle School Teacher",
    "template": "education"
  },
  {
    "title": "Associate UI Designer",
    "template": "creative_media"
  },
  {
    "title": "Senior HVAC Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Senior Courier",
    "template": "logistics_transport"
  },
  {
    "title": "Senior Executive Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 2 Customer Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Director of Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Lead Frontend Developer",
    "template": "software_engineering"
  },
  {
    "title": "Junior Network Administrator",
    "template": "it_ops"
  },
  {
    "title": "Lead Staff Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Lead Nurse Practitioner",
    "template": "healthcare_clinical"
  },
  {
    "title": "Assistant Middle School Teacher",
    "template": "education"
  },
  {
    "title": "Director of UI Designer",
    "template": "creative_media"
  },
  {
    "title": "Lead HVAC Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Lead Courier",
    "template": "logistics_transport"
  },
  {
    "title": "Lead Executive Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 3 Customer Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Senior Inside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Principal Frontend Developer",
    "template": "software_engineering"
  },
  {
    "title": "Manager Network Administrator",
    "template": "it_ops"
  },
  {
    "title": "Associate Staff Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Charge Nurse Practitioner",
    "template": "healthcare_clinical"
  },
  {
    "title": "Associate Middle School Teacher",
    "template": "education"
  },
  {
    "title": "Senior UX Designer",
    "template": "creative_media"
  },
  {
    "title": "Apprentice HVAC Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Assistant Courier",
    "template": "logistics_transport"
  },
  {
    "title": "Assistant Executive Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Senior Client Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Lead Inside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Staff Frontend Developer",
    "template": "software_engineering"
  },
  {
    "title": "Director of Network Administrator",
    "template": "it_ops"
  },
  {
    "title": "Manager Staff Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Clinical Nurse Practitioner",
    "template": "healthcare_clinical"
  },
  {
    "title": "Director of Middle School Teacher",
    "template": "education"
  },
  {
    "title": "Lead UX Designer",
    "template": "creative_media"
  },
  {
    "title": "Journeyman HVAC Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Associate Courier",
    "template": "logistics_transport"
  },
  {
    "title": "Associate Executive Assistant",
    "template": "clerical_admin"
  },
  {
    "title": "Lead Client Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Associate Inside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Junior Backend Developer",
    "template": "software_engineering"
  },
  {
    "title": "Senior IT Support Specialist",
    "template": "it_ops"
  },
  {
    "title": "Director of Staff Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Senior Physician Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Senior High School Teacher",
    "template": "education"
  },
  {
    "title": "Assistant UX Designer",
    "template": "creative_media"
  },
  {
    "title": "Senior Welder",
    "template": "skilled_trades"
  },
  {
    "title": "Manager Courier",
    "template": "logistics_transport"
  },
  {
    "title": "Senior Receptionist",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 1 Client Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Manager Inside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Senior Backend Developer",
    "template": "software_engineering"
  },
  {
    "title": "Lead IT Support Specialist",
    "template": "it_ops"
  },
  {
    "title": "Senior Senior Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Lead Physician Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Lead High School Teacher",
    "template": "education"
  },
  {
    "title": "Associate UX Designer",
    "template": "creative_media"
  },
  {
    "title": "Lead Welder",
    "template": "skilled_trades"
  },
  {
    "title": "Senior Dispatcher",
    "template": "logistics_transport"
  },
  {
    "title": "Lead Receptionist",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 2 Client Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Director of Inside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Lead Backend Developer",
    "template": "software_engineering"
  },
  {
    "title": "Junior IT Support Specialist",
    "template": "it_ops"
  },
  {
    "title": "Lead Senior Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Charge Physician Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Assistant High School Teacher",
    "template": "education"
  },
  {
    "title": "Director of UX Designer",
    "template": "creative_media"
  },
  {
    "title": "Apprentice Welder",
    "template": "skilled_trades"
  },
  {
    "title": "Lead Dispatcher",
    "template": "logistics_transport"
  },
  {
    "title": "Assistant Receptionist",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 3 Client Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Senior Outside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Principal Backend Developer",
    "template": "software_engineering"
  },
  {
    "title": "Manager IT Support Specialist",
    "template": "it_ops"
  },
  {
    "title": "Associate Senior Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Clinical Physician Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Associate High School Teacher",
    "template": "education"
  },
  {
    "title": "Senior Product Designer",
    "template": "creative_media"
  },
  {
    "title": "Journeyman Welder",
    "template": "skilled_trades"
  },
  {
    "title": "Assistant Dispatcher",
    "template": "logistics_transport"
  },
  {
    "title": "Associate Receptionist",
    "template": "clerical_admin"
  },
  {
    "title": "Senior Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Lead Outside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Staff Backend Developer",
    "template": "software_engineering"
  },
  {
    "title": "Director of IT Support Specialist",
    "template": "it_ops"
  },
  {
    "title": "Manager Senior Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Senior Medical Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Director of High School Teacher",
    "template": "education"
  },
  {
    "title": "Lead Product Designer",
    "template": "creative_media"
  },
  {
    "title": "Senior Carpenter",
    "template": "skilled_trades"
  },
  {
    "title": "Associate Dispatcher",
    "template": "logistics_transport"
  },
  {
    "title": "Senior Office Manager",
    "template": "clerical_admin"
  },
  {
    "title": "Lead Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Associate Outside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Junior Full Stack Developer",
    "template": "software_engineering"
  },
  {
    "title": "Senior IT Technician",
    "template": "it_ops"
  },
  {
    "title": "Director of Senior Accountant",
    "template": "finance_accounting"
  },
  {
    "title": "Lead Medical Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Senior Special Education Teacher",
    "template": "education"
  },
  {
    "title": "Assistant Product Designer",
    "template": "creative_media"
  },
  {
    "title": "Lead Carpenter",
    "template": "skilled_trades"
  },
  {
    "title": "Manager Dispatcher",
    "template": "logistics_transport"
  },
  {
    "title": "Lead Office Manager",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 1 Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Manager Outside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Senior Full Stack Developer",
    "template": "software_engineering"
  },
  {
    "title": "Lead IT Technician",
    "template": "it_ops"
  },
  {
    "title": "Senior Bookkeeper",
    "template": "finance_accounting"
  },
  {
    "title": "Charge Medical Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Lead Special Education Teacher",
    "template": "education"
  },
  {
    "title": "Associate Product Designer",
    "template": "creative_media"
  },
  {
    "title": "Apprentice Carpenter",
    "template": "skilled_trades"
  },
  {
    "title": "Senior Logistics Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Assistant Office Manager",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 2 Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Director of Outside Sales Representative",
    "template": "sales_marketing"
  },
  {
    "title": "Lead Full Stack Developer",
    "template": "software_engineering"
  },
  {
    "title": "Junior IT Technician",
    "template": "it_ops"
  },
  {
    "title": "Lead Bookkeeper",
    "template": "finance_accounting"
  },
  {
    "title": "Clinical Medical Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Assistant Special Education Teacher",
    "template": "education"
  },
  {
    "title": "Director of Product Designer",
    "template": "creative_media"
  },
  {
    "title": "Journeyman Carpenter",
    "template": "skilled_trades"
  },
  {
    "title": "Lead Logistics Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Associate Office Manager",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 3 Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Senior Account Executive",
    "template": "sales_marketing"
  },
  {
    "title": "Principal Full Stack Developer",
    "template": "software_engineering"
  },
  {
    "title": "Manager IT Technician",
    "template": "it_ops"
  },
  {
    "title": "Associate Bookkeeper",
    "template": "finance_accounting"
  },
  {
    "title": "Senior Clinical Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Associate Special Education Teacher",
    "template": "education"
  },
  {
    "title": "Senior Motion Designer",
    "template": "creative_media"
  },
  {
    "title": "Senior Machinist",
    "template": "skilled_trades"
  },
  {
    "title": "Assistant Logistics Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Senior Office Administrator",
    "template": "clerical_admin"
  },
  {
    "title": "Senior Technical Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Lead Account Executive",
    "template": "sales_marketing"
  },
  {
    "title": "Staff Full Stack Developer",
    "template": "software_engineering"
  },
  {
    "title": "Director of IT Technician",
    "template": "it_ops"
  },
  {
    "title": "Manager Bookkeeper",
    "template": "finance_accounting"
  },
  {
    "title": "Lead Clinical Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Director of Special Education Teacher",
    "template": "education"
  },
  {
    "title": "Lead Motion Designer",
    "template": "creative_media"
  },
  {
    "title": "Lead Machinist",
    "template": "skilled_trades"
  },
  {
    "title": "Associate Logistics Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Lead Office Administrator",
    "template": "clerical_admin"
  },
  {
    "title": "Lead Technical Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Associate Account Executive",
    "template": "sales_marketing"
  },
  {
    "title": "Junior Mobile Developer",
    "template": "software_engineering"
  },
  {
    "title": "Senior IT Analyst",
    "template": "it_ops"
  },
  {
    "title": "Director of Bookkeeper",
    "template": "finance_accounting"
  },
  {
    "title": "Charge Clinical Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Senior Substitute Teacher",
    "template": "education"
  },
  {
    "title": "Assistant Motion Designer",
    "template": "creative_media"
  },
  {
    "title": "Apprentice Machinist",
    "template": "skilled_trades"
  },
  {
    "title": "Manager Logistics Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Assistant Office Administrator",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 1 Technical Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Manager Account Executive",
    "template": "sales_marketing"
  },
  {
    "title": "Senior Mobile Developer",
    "template": "software_engineering"
  },
  {
    "title": "Lead IT Analyst",
    "template": "it_ops"
  },
  {
    "title": "Senior Accounting Specialist",
    "template": "finance_accounting"
  },
  {
    "title": "Clinical Clinical Assistant",
    "template": "healthcare_clinical"
  },
  {
    "title": "Lead Substitute Teacher",
    "template": "education"
  },
  {
    "title": "Associate Motion Designer",
    "template": "creative_media"
  },
  {
    "title": "Journeyman Machinist",
    "template": "skilled_trades"
  },
  {
    "title": "Senior Supply Chain Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Associate Office Administrator",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 2 Technical Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Director of Account Executive",
    "template": "sales_marketing"
  },
  {
    "title": "Lead Mobile Developer",
    "template": "software_engineering"
  },
  {
    "title": "Junior IT Analyst",
    "template": "it_ops"
  },
  {
    "title": "Lead Accounting Specialist",
    "template": "finance_accounting"
  },
  {
    "title": "Senior Physical Therapist",
    "template": "healthcare_clinical"
  },
  {
    "title": "Assistant Substitute Teacher",
    "template": "education"
  },
  {
    "title": "Director of Motion Designer",
    "template": "creative_media"
  },
  {
    "title": "Senior Maintenance Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Lead Supply Chain Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Senior Operations Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Tier 3 Technical Support Specialist",
    "template": "customer_support"
  },
  {
    "title": "Senior Account Manager",
    "template": "sales_marketing"
  },
  {
    "title": "Principal Mobile Developer",
    "template": "software_engineering"
  },
  {
    "title": "Manager IT Analyst",
    "template": "it_ops"
  },
  {
    "title": "Associate Accounting Specialist",
    "template": "finance_accounting"
  },
  {
    "title": "Lead Physical Therapist",
    "template": "healthcare_clinical"
  },
  {
    "title": "Associate Substitute Teacher",
    "template": "education"
  },
  {
    "title": "Senior Video Editor",
    "template": "creative_media"
  },
  {
    "title": "Lead Maintenance Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Assistant Supply Chain Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Lead Operations Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Senior Help Desk Representative",
    "template": "customer_support"
  },
  {
    "title": "Lead Account Manager",
    "template": "sales_marketing"
  },
  {
    "title": "Staff Mobile Developer",
    "template": "software_engineering"
  },
  {
    "title": "Director of IT Analyst",
    "template": "it_ops"
  },
  {
    "title": "Manager Accounting Specialist",
    "template": "finance_accounting"
  },
  {
    "title": "Charge Physical Therapist",
    "template": "healthcare_clinical"
  },
  {
    "title": "Director of Substitute Teacher",
    "template": "education"
  },
  {
    "title": "Lead Video Editor",
    "template": "creative_media"
  },
  {
    "title": "Apprentice Maintenance Technician",
    "template": "skilled_trades"
  },
  {
    "title": "Associate Supply Chain Coordinator",
    "template": "logistics_transport"
  },
  {
    "title": "Assistant Operations Coordinator",
    "template": "clerical_admin"
  },
  {
    "title": "Lead Help Desk Representative",
    "template": "customer_support"
  },
  {
    "title": "Associate Account Manager",
    "template": "sales_marketing"
  },
  {
    "title": "Junior iOS Developer",
    "template": "software_engineering"
  },
  {
    "title": "Senior DevOps Engineer",
    "template": "it_ops"
  }
];

export const JOB_ALIASES = {
  "developer": "Software Engineer",
  "programmer": "Software Engineer",
  "helpdesk": "IT Support Specialist",
  "call centre agent": "Call Center Agent",
  "truckdriver": "Truck Driver",
  "book keeper": "Bookkeeper",
  "social media": "Social Media Manager",
  "ux": "UX Designer"
};
